language: android

android:
  components:
    - platform-tools
    - android-27
    - build-tools-27.0.3
    - extra-android-m2repository

licenses:
    - android-sdk-license-.+

env:
  -  TERM=dumb

script:
  - ./gradlew build
